name: Publish to Qiita

on:
  push:
    paths:
      - 'content/ja/**.md'

jobs:
  publish-qiita:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Publish to Qiita
        run: |
          CHANGED_FILES="$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^content/ja/.*\\.md$' || true)"
          if [ -z "$CHANGED_FILES" ]; then
            echo 'No Japanese markdown files changed. Skipping.'
            exit 0
          fi
          npx ts-node scripts/publish_qiita.ts $CHANGED_FILES
        env:
          QIITA_TOKEN: ${{ secrets.QIITA_TOKEN }}
